#------------------------------------------------------------------------------------------------------
#                           ANTI XRAY HEURISTICS (AXH) - by __Mithrandir__
#
#    Disclaimer: This plugin may not function as intended with servers with custom or modified
#    terrain and ores generation.
#------------------------------------------------------------------------------------------------------

#If true, AXH will output debug messages (no need to activate this unless a developer requests it):
Debug: false

#----------------------------------------------
#HEURISTICALLY BASED MONITORING CONFIGURATIONS:
#----------------------------------------------

#AXH will only monitor player behaviour in order to detect xrays in certain worlds. Only nether and overworld world
#types will be considered from following lists:
TrackWorlds:
  - 'world'
  - 'world_nether'

#The following values are to be balanced depending on the world's mineral density. Default values should be ok for
#regular mineral generation. Set to 0 to ignore. Negative values will reduce player suspicion and/or cause unintended
#internal calculation outputs (not recommended).
#There are various internal factors that may increment or ignore these weights depending on certain player behaviour.
CoalWeight: 5.0
IronWeight: 5.0
GoldWeight: 5.0
LapisWeight: 12.0
RedstoneWeight: 9.0
EmeraldWeight: 28.0
DiamondWeight: 20.0
QuartzWeight: 5.0
NetherGoldWeight: 5.0
AncientDebrisWeight: 28.0

#You can use these reducers for certain biomes where ores are more abundant. They are used internally in order to
#reduce the total amount of suspicion applied according to the algorithm, when an ore is mined in a biome where it's
#more frequent (Example: Gold (Mesa), Emerald (ExtremeHills)), the higher, the more weight is reduced:
FinalEmeraldWeightDivisionReducer: 2
FinalGoldWeightDivisionReducer: 4

#For further efficiency, let AXH know how many adjacent blocks in any direction should be considered as part of
#a same ore vein. Default should be ok for default vanilla ore generation, set to 0 or less to disable:
ConsiderAdjacentWithinDistance: 10

#For further efficiency, let AXH know how many blocks a player would have to mine at very least, in order to
#encounter another ore vein. This value should be more or less the average minimum distance between veins on your
#server's map, default should be ok for default vanilla ore generation. Setting this to a lower value than default
#is not recommended at all (and your server shouldn't even have a higher ore density than vanilla, else you wouldn't
#be using this plugin), but you can if you're crazy enough.
MinimumBlocksMinedToNextVein: 10

#Ignore mined blocks above following altitude in the overworld (default value should be ok):
IgnoreHigherThanOverworldAltitude: 65
#Ignore mined blocks above following altitude in the nether (default value should be ok):
IgnoreHigherThanNetherAltitude: 120

#------------------------------------------------------
#AUTOMATIC XRAYER HANDLING & PUNISHMENT CONFIGURATIONS:
#------------------------------------------------------

#If set to true, the player's items will be stored (even before a configurable clense) which will later be revisable.
#This includes HotBar, OffHand, Inventory and Equipment.
#(View "STORAGE CONFIGURATION" for details on how the persistent memory storage can be configured)
StoreCopy: true

#If set to true, all of the player's items will be erased. This includes HotBar, OffHand, Inventory and Equipment.
#Warning: This should be set to true if StoreCopy is true, else player absolving will result in duplications:
ClensePlayerItems: true

#If set to true, players punished for xraying will receive a message ("PlayerMessageOnXray" in locale.yml) when detected
#for xraying.
SendMessageToPlayer: false

#Recommended true. If so, will nullify the player's suspicion after being punished:
NullifySuspicionAferPunish: true

#The following command arrays are to be executed from console in different (specified for each) moments.

#Commands that will be executed when an xrayer is detected.
#In the following example, the first number represents the amount of consecutive detections necessary for the command
#to be executed, and within it, the commands to execute in order, for example:
#    1:
#        1: 'say {PlayerName} was detected Xraying'
#        2: 'say proceeding to automatically handle as Xrayer'
#    2:
#        1: 'say {PlayerName} was detected Xraying {TimesDetected} times'
#Will execute the first two say commands the first time that the xrayer is detected only, and the third say command
#on the second detection only.
#Set the array of commands to empty like this: CommandsExecutedOnXrayerDetected: [] , if you wish to disable command
#executions for the case.
#Available placeholders for following arrays and strings (Caps sensitive): {PlayerName}, {TimesDetected}
CommandsExecutedOnXrayerDetected: []

#Commands that will be executed when an xrayer is absolved, If you wish to add commands, remove the [] and add them
#on each following line:
#    - 'say {PlayerName} was absolved from being considered an Xrayer'
#Will execute the say command when any xrayer is absolved.
#As you can see, commands for this single array do not require a preceding number, since the amount of times detected is
#irrelevant.
#Set the array of commands to empty like this: CommandsExecutedOnPlayerAbsolved: [] , if you wish to disable command
#executions for the case.
#Available placeholders for this array (Case sensitive): {PlayerName}
CommandsExecutedOnPlayerAbsolved: []

#If set to true, players with the permission AXH.XrayerWarning will be notified (with the message "AutoHandledPlayer"
#in locale.yml) if an xrayer was found and dealt with.
TellPlayersWithPermission: true

#----------------------
#STORAGE CONFIGURATION:
#----------------------
#AXH needs to store certain persistent information, here you should configure your preferred method for data storing.

#Storage type (available: 'MYSQL', 'JSON')
#Be warned: AAX does not offer data conversion between available storage types, so choose your data storage
#wisely before you start using this plugin. The storage type will be swapped once you change it on this config and
#restart the server. If you don't even know what the storage types are and how they work, just leave the default
#JSON and don't change it, it will do just fine and requires no further setups:
StorageType: 'JSON'

#Edit the following credentials if you are using MySQL:
SQLHost: '127.0.0.1'
SQLPort: '3306'
SQLDatabaseName: 'myDatabase'
SQLUsername: 'root'
SQLPassword: 'root'
SQLMaxActiveConnections: 10